frr version 10.6.0
frr defaults traditional
hostname ospf1
log syslog informational
log file /var/log/frr/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
interface ens19
 description net_router1
 ip address 192.168.10.1/24
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
interface ens20
 description r1-r3
 ip address 10.0.12.1/30
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
interface ens21
 description r1-r2
 ip address 10.0.10.1/30
 ip ospf cost 1000
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
router ospf
 ospf router-id 1.1.1.1
 network 10.0.10.0/30 area 0
 network 10.0.12.0/30 area 0
 network 192.168.10.0/24 area 0
 neighbor 10.0.10.2
 neighbor 10.0.12.2
exit
!
