frr version 10.6.0
frr defaults traditional
hostname ospf3
log syslog informational
log file /var/log/frr/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
interface ens19
 description net_router3
 ip address 192.168.30.1/24
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
interface ens20
 description r3-r2
 ip address 10.0.11.1/30
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
interface ens21
 description r3-r1
 ip address 10.0.12.2/30
 ip ospf dead-interval 30
 ip ospf mtu-ignore
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 10.0.11.0/30 area 0
 network 10.0.12.0/30 area 0
 network 192.168.30.0/24 area 0
 neighbor 10.0.11.2
 neighbor 10.0.12.1
exit
!
