network:
  version: 2
  ethernets:
    ens18:
      addresses:
      - "192.168.11.38/24"
      routes:
      - to: "default"
        via: "192.168.11.1"
    ens19:
      addresses:
      - "192.168.255.13/30"
      routes:
      - to: "192.168.0.0/16"
        via: "192.168.255.14"

